# Generated by Django 2.0.6 on 2019-02-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentcard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historycard',
            name='date',
        ),
    ]
