# Generated by Django 2.0.6 on 2019-02-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190210_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currentCard',
        ),
        migrations.DeleteModel(
            name='historyCard',
        ),
    ]
