# Generated by Django 2.0.6 on 2019-02-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_currentcard_historycard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currentCard',
        ),
        migrations.DeleteModel(
            name='historyCard',
        ),
    ]
