# Generated by Django 2.0.6 on 2019-02-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_currentcard_historycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentCard2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.CharField(max_length=100)),
                ('typeCard', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('currenttime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='historyCard2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.CharField(max_length=100)),
                ('typeCard', models.CharField(max_length=50)),
                ('compare', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('currenttime', models.CharField(max_length=50)),
            ],
        ),
    ]
