# Generated by Django 2.0.6 on 2019-02-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_currentcard2_historycard2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currentCard2',
        ),
        migrations.DeleteModel(
            name='historyCard2',
        ),
    ]
