# Generated by Django 2.0.6 on 2019-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_currentcard2_historycard2'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.CharField(max_length=100)),
                ('actionCard', models.CharField(max_length=50)),
                ('timestampID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='currentCard',
        ),
        migrations.DeleteModel(
            name='currentCard2',
        ),
        migrations.DeleteModel(
            name='historyCard',
        ),
        migrations.DeleteModel(
            name='historyCard2',
        ),
    ]
