# Generated by Django 2.0.6 on 2019-02-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190224_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cardRecord',
        ),
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
