# Generated by Django 2.0.6 on 2019-02-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_cardrecord_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
