# Generated by Django 2.0.6 on 2019-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=50)),
            ],
        ),
    ]
