# Generated by Django 2.0.6 on 2019-02-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
