# Generated by Django 2.0.6 on 2019-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0024_delete_cardrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.CharField(max_length=100)),
                ('actionCard', models.CharField(max_length=50)),
                ('timestampID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=50)),
                ('changeReq', models.CharField(max_length=100)),
            ],
        ),
    ]
