# Generated by Django 2.0.6 on 2019-02-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_cardrecord_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cardRecord',
        ),
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
