# Generated by Django 2.0.6 on 2019-02-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_cardrecord_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cardRecord',
        ),
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
