# Generated by Django 2.0.6 on 2019-03-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20190304_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrecord',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='cardRecord',
        ),
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
