# Generated by Django 2.0.6 on 2019-03-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20190312_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrecord',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='cardRecord',
        ),
        migrations.DeleteModel(
            name='timeStamp',
        ),
    ]
