# Generated by Django 2.0.6 on 2019-04-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_register_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_id',
        ),
    ]
