# Generated by Django 2.0.6 on 2019-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=500)),
            ],
        ),
    ]
