# Generated by Django 2.0.6 on 2019-04-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_board',
        ),
    ]
