# Generated by Django 2.0.6 on 2019-04-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_record',
            name='action_card',
        ),
        migrations.RemoveField(
            model_name='card_record',
            name='comment_card',
        ),
        migrations.RemoveField(
            model_name='card_record',
            name='desc_card',
        ),
        migrations.RemoveField(
            model_name='card_record',
            name='listafter_card',
        ),
        migrations.RemoveField(
            model_name='card_record',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='change_record',
            name='timestamp',
        ),
    ]
