# Generated by Django 2.0.6 on 2019-04-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190415_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_record',
            name='action_card',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_record',
            name='comment_card',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_record',
            name='desc_card',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_record',
            name='listafter_card',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_record',
            name='timestamp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.time_stamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_record',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change_record',
            name='timestamp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.time_stamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change_record',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
