# Generated by Django 2.0.6 on 2019-04-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190415_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_record',
            name='timestamp',
        ),
    ]
