# Generated by Django 2.0.6 on 2019-04-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_card_record_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_record',
            name='timestamp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.time_stamp'),
            preserve_default=False,
        ),
    ]
