# Generated by Django 2.0.6 on 2019-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_card_record_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_record',
            name='board',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change_record',
            name='board',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
