# Generated by Django 2.0.6 on 2019-04-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190416_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_record_effort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=100)),
                ('action_card', models.CharField(max_length=100)),
                ('custom_name', models.CharField(max_length=100)),
                ('current_value', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=100)),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.time_stamp')),
            ],
        ),
        migrations.CreateModel(
            name='change_effort_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=500)),
                ('amount_change', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='change_record',
            name='timestamp',
            field=models.IntegerField(default='0'),
        ),
    ]
