# Generated by Django 2.0.6 on 2019-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190416_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_record',
            name='timestamp',
            field=models.IntegerField(default='0'),
        ),
    ]
