# Generated by Django 2.0.6 on 2019-05-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_card_effort_record_change_effort_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_movement_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=100)),
                ('action_card', models.CharField(max_length=100)),
                ('listafter_movement_card', models.CharField(max_length=50)),
                ('listbefore_movement_card', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='change_movement_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('planning_doing', models.IntegerField(default='0')),
                ('planning_testing', models.IntegerField(default='0')),
                ('planning_done', models.IntegerField(default='0')),
                ('doing_planning', models.IntegerField(default='0')),
                ('doing_testing', models.IntegerField(default='0')),
                ('doing_done', models.IntegerField(default='0')),
                ('testing_planning', models.IntegerField(default='0')),
                ('testing_doing', models.IntegerField(default='0')),
                ('testing_done', models.IntegerField(default='0')),
                ('done_planning', models.IntegerField(default='0')),
                ('done_doing', models.IntegerField(default='0')),
                ('done_testing', models.IntegerField(default='0')),
                ('timestamp', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='time_stamp_movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='card_movement_record',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.time_stamp_movement'),
        ),
    ]
