# Generated by Django 2.0.6 on 2019-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20190509_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_storypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=500)),
                ('storypoint', models.CharField(max_length=10)),
                ('timestamp', models.IntegerField(default='0')),
            ],
        ),
    ]
