# Generated by Django 2.0.6 on 2019-06-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_caca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caca',
        ),
    ]
